import Nav from '@/components/Nav'
import AuthProvider from '@/components/Providers/AuthProvider'
import CssBaselineProvider from '@/components/Providers/CSSBaselineProvider'
import ReduxProvider from '@/components/Providers/ReduxProvider'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>
                    <ReduxProvider>
                        <CssBaselineProvider>
                            <Nav
                                links={[
                                    { label: 'Home', href: '/' },
                                    { label: 'About', href: '/about' },
                                    { label: 'List', href: '/list' },
                                ]}
                            />
                            {children}
                        </CssBaselineProvider>
                    </ReduxProvider>
                </AuthProvider>
            </body>
        </html>
    )
}
